### PR TITLE
Explicitly unwrap unique_ptrs in dynamic_casts

### PR DESCRIPTION
**Pull request by GreenLightning**
This change explicitly calls `get()` on `unique_ptr`s when they are used in a `dynamic_cast`. This must be the intended behavior, because the target type of the casts is a regular pointer and not a smart pointer, but I am not sure by which C++ mechanism this is currently achieved (i.e. `unique_ptr` should not be implicitly convertible to a regular pointer and the [documentation](https://en.cppreference.com/w/cpp/language/dynamic_cast) for `dynamic_cast` does not mention smart pointers at all).

`get()` is [safe](https://en.cppreference.com/w/cpp/memory/unique_ptr/get) to call on empty `unique_ptr`s, in which case it returns `nullptr`. Please also refer to [line 821](https://github.com/nmwsharp/happly/blob/cfa2611550bc7da65855a78af0574b65deb81766/happly.h#L821) where it is already called explicitly.

This fixes the compilation errors mentioned in #30 and the code now compiles using nvcc (tested with version 11.1).

### CODE REVIEW

**Comment by nmwsharp** [comment]
Thank you for this!! The fix make total sense. I'm not really sure how the old code worked either, probably not worth thinking about.

Please excuse me for taking 2 years to merge your simple fix :)
